import type { ResidentSnapshot } from "@/components/resident-snapshots/types";

function daysAgo(days: number) {
  const now = new Date();
  now.setDate(now.getDate() - days);
  return now.toISOString();
}

export const MOCK_RESIDENT_SNAPSHOTS: ResidentSnapshot[] = [
  {
    id: "mock-1",
    firstName: "Mary",
    lastName: "Thompson",
    fullName: "Mary Thompson",
    preferredName: "Mary",
    room: "214B",
    status: "ACTIVE",
    admissionDate: "2026-02-11T00:00:00.000Z",
    birthDate: "1941-09-16T00:00:00.000Z",
    tags: ["Loves Music", "Nail Care", "Prefers 1:1", "Needs Encouragement"],
    interests: ["Classic country", "Nail care", "Family stories"],
    dislikes: ["Loud morning groups"],
    favoriteActivities: ["Nail painting", "Music social"],
    favoriteTopics: ["Grandchildren", "Church choir"],
    favoriteMusic: ["Dolly Parton", "Hymns"],
    favoriteMedia: ["Classic movies"],
    independentActivities: ["Photo albums", "Magazine browsing"],
    participationStyle: "Watches first, then joins with encouragement",
    bestTimeOfDay: "Afternoons",
    groupParticipationNotes: "More likely to join after seeing peers start.",
    oneToOneStyle: "Very receptive to calm 1:1 visits.",
    commonRefusals: "Declines early morning group invites.",
    whatWorks: "Warm approach, offer choices, mention music first.",
    whatDoesNotWork: "Quick transitions or crowded spaces.",
    supportNeeds: ["Needs Cueing", "Prefers Quiet Setting", "Low Energy"],
    quickSummary: "Watches first, then joins with encouragement",
    sourceNotes: null,
    sourcePreferences: null,
    sourceSafetyNotes: null,
    lastEngagementDate: daysAgo(2),
    lastActivity: "Attended music circle and smiled while singing chorus lines.",
    lastOneToOne: "Room visit with nail painting and family conversation.",
    lastNoteDate: daysAgo(1),
    lastAiSuggestion: "Use a 12-minute hymn-themed social starter.",
    dischargeDate: null,
    dischargeReason: null
  },
  {
    id: "mock-2",
    firstName: "James",
    lastName: "Carter",
    fullName: "James Carter",
    preferredName: "Jim",
    room: "102B",
    status: "ACTIVE",
    admissionDate: "2026-03-21T00:00:00.000Z",
    birthDate: "1938-04-28T00:00:00.000Z",
    tags: ["Sports Fan", "Group-Friendly", "Social"],
    interests: ["Baseball", "Card games", "Sports trivia"],
    dislikes: ["Long lectures"],
    favoriteActivities: ["Sports recap", "Table games"],
    favoriteTopics: ["Cubs history", "Military service"],
    favoriteMusic: ["50s oldies"],
    favoriteMedia: ["Sports highlights"],
    independentActivities: ["Score sheet tracking"],
    participationStyle: "Social in small groups and card tables",
    bestTimeOfDay: "Mid-morning",
    groupParticipationNotes: "Responds well when paired with one familiar peer.",
    oneToOneStyle: "Likes quick sports check-ins.",
    commonRefusals: "Declines crafts.",
    whatWorks: "Use sports prompts and point-based games.",
    whatDoesNotWork: "Overly passive activities.",
    supportNeeds: ["Enjoys Social Settings", "Better in Small Groups"],
    quickSummary: "Social in small groups and card tables",
    sourceNotes: null,
    sourcePreferences: null,
    sourceSafetyNotes: null,
    lastEngagementDate: daysAgo(1),
    lastActivity: "Played cards with peers and initiated score keeping.",
    lastOneToOne: "Brief room check-in around baseball standings.",
    lastNoteDate: daysAgo(1),
    lastAiSuggestion: "Run a 15-minute sports headline challenge.",
    dischargeDate: null,
    dischargeReason: null
  },
  {
    id: "mock-3",
    firstName: "Louise",
    lastName: "Bryant",
    fullName: "Louise Bryant",
    preferredName: null,
    room: "110C",
    status: "ACTIVE",
    admissionDate: "2025-11-08T00:00:00.000Z",
    birthDate: "1939-12-02T00:00:00.000Z",
    tags: ["Crafts", "Quiet", "Needs Encouragement"],
    interests: ["Seasonal crafts", "Devotional readings"],
    dislikes: ["Fast-paced games"],
    favoriteActivities: ["Guided crafts", "Devotional group"],
    favoriteTopics: ["Family recipes", "Faith community"],
    favoriteMusic: ["Gospel"],
    favoriteMedia: ["Hallmark movies"],
    independentActivities: ["Coloring pages"],
    participationStyle: "Engages with guided prompts and clear structure",
    bestTimeOfDay: "Late morning",
    groupParticipationNotes: "Prefers seated groups with low noise.",
    oneToOneStyle: "Open to short check-ins with visual prompts.",
    commonRefusals: "Declines loud game rooms.",
    whatWorks: "Offer pre-set craft kits and simple instructions.",
    whatDoesNotWork: "Rapid transitions.",
    supportNeeds: ["Prefers Quiet Setting", "Short Attention Span"],
    quickSummary: "Engages with guided prompts and clear structure",
    sourceNotes: null,
    sourcePreferences: null,
    sourceSafetyNotes: null,
    lastEngagementDate: daysAgo(4),
    lastActivity: "Completed spring card craft with moderate cueing.",
    lastOneToOne: "Reviewed devotional reading and discussed family updates.",
    lastNoteDate: daysAgo(3),
    lastAiSuggestion: "Use a 20-minute guided craft with visual step cards.",
    dischargeDate: null,
    dischargeReason: null
  },
  {
    id: "mock-4",
    firstName: "Harold",
    lastName: "Dean",
    fullName: "Harold Dean",
    preferredName: "Hal",
    room: "118B",
    status: "ACTIVE",
    admissionDate: "2026-01-05T00:00:00.000Z",
    birthDate: "1936-07-20T00:00:00.000Z",
    tags: ["Word Searches", "Crosswords", "Prefers 1:1"],
    interests: ["Word games", "History talks"],
    dislikes: ["Noisy activity rooms"],
    favoriteActivities: ["Crosswords", "Word search rounds"],
    favoriteTopics: ["Local history", "Travel stories"],
    favoriteMusic: ["Big band"],
    favoriteMedia: ["History channel"],
    independentActivities: ["Puzzle books"],
    participationStyle: "Quiet observer in group, stronger in 1:1",
    bestTimeOfDay: "Afternoons",
    groupParticipationNotes: "Best in small-group settings under 6 residents.",
    oneToOneStyle: "Very engaged when puzzle prompts are provided.",
    commonRefusals: "Declines competitive games.",
    whatWorks: "Bring printed puzzles and history prompts.",
    whatDoesNotWork: "High-volume or open-floor trivia.",
    supportNeeds: ["Hearing Support", "Prefers Quiet Setting"],
    quickSummary: "Quiet observer in group, stronger in 1:1",
    sourceNotes: null,
    sourcePreferences: null,
    sourceSafetyNotes: null,
    lastEngagementDate: daysAgo(3),
    lastActivity: "Completed themed crossword with one-to-one support.",
    lastOneToOne: "Discussed travel memories while doing word search.",
    lastNoteDate: daysAgo(2),
    lastAiSuggestion: "Prepare a 12-question local-history puzzle set.",
    dischargeDate: null,
    dischargeReason: null
  },
  {
    id: "mock-5",
    firstName: "Eleanor",
    lastName: "Price",
    fullName: "Eleanor Price",
    preferredName: "Ellie",
    room: "214A",
    status: "ACTIVE",
    admissionDate: "2026-04-01T00:00:00.000Z",
    birthDate: "1945-01-03T00:00:00.000Z",
    tags: ["Bed-Bound", "Sensory", "Prefers 1:1"],
    interests: ["Poetry", "Photo albums", "Soft music"],
    dislikes: ["Long transitions"],
    favoriteActivities: ["Sensory basket", "Photo reminiscence"],
    favoriteTopics: ["Pets", "Nature scenes"],
    favoriteMusic: ["Soft piano"],
    favoriteMedia: ["Nature documentaries"],
    independentActivities: ["Photo cards"],
    participationStyle: "Responds best to short bedside interactions",
    bestTimeOfDay: "Early afternoon",
    groupParticipationNotes: "Usually declines group due to endurance.",
    oneToOneStyle: "Accepts calm 1:1 with sensory items.",
    commonRefusals: "Refuses long sessions.",
    whatWorks: "Short visits, soft tone, offer two choices.",
    whatDoesNotWork: "Fast-paced large groups.",
    supportNeeds: ["Bed-Bound", "Benefits from Sensory Items", "Low Energy"],
    quickSummary: "Responds best to short bedside interactions",
    sourceNotes: null,
    sourcePreferences: null,
    sourceSafetyNotes: null,
    lastEngagementDate: daysAgo(1),
    lastActivity: "Bedside sensory basket and poetry reading.",
    lastOneToOne: "Photo reminiscence with calm conversation.",
    lastNoteDate: daysAgo(1),
    lastAiSuggestion: "Use a 7-minute bedside sensory-and-poetry combo.",
    dischargeDate: null,
    dischargeReason: null
  },
  {
    id: "mock-6",
    firstName: "Rosa",
    lastName: "Mendez",
    fullName: "Rosa Mendez",
    preferredName: null,
    room: "121A",
    status: "ACTIVE",
    admissionDate: "2025-10-12T00:00:00.000Z",
    birthDate: "1940-06-14T00:00:00.000Z",
    tags: ["Music", "Social", "Group-Friendly"],
    interests: ["Latin music", "Dancing in chair"],
    dislikes: ["Silent activities"],
    favoriteActivities: ["Music socials", "Rhythm group"],
    favoriteTopics: ["Family celebrations"],
    favoriteMusic: ["Bolero", "Salsa classics"],
    favoriteMedia: ["Music videos"],
    independentActivities: ["Lyric sheets"],
    participationStyle: "Highly social and energized by group music",
    bestTimeOfDay: "Late afternoon",
    groupParticipationNotes: "Excellent peer encourager.",
    oneToOneStyle: "Short check-ins between groups.",
    commonRefusals: "Rarely refuses music-related programming.",
    whatWorks: "Lead with rhythm and familiar songs.",
    whatDoesNotWork: "Low-stimulation silent sessions.",
    supportNeeds: ["Enjoys Social Settings"],
    quickSummary: "Highly social and energized by group music",
    sourceNotes: null,
    sourcePreferences: null,
    sourceSafetyNotes: null,
    lastEngagementDate: daysAgo(2),
    lastActivity: "Led singalong section during afternoon music social.",
    lastOneToOne: "Quick hallway check-in about favorite songs.",
    lastNoteDate: daysAgo(2),
    lastAiSuggestion: "Use a call-and-response rhythm warm-up.",
    dischargeDate: null,
    dischargeReason: null
  },
  {
    id: "mock-7",
    firstName: "Victor",
    lastName: "Lang",
    fullName: "Victor Lang",
    preferredName: null,
    room: "203C",
    status: "ACTIVE",
    admissionDate: "2025-09-18T00:00:00.000Z",
    birthDate: "1937-02-11T00:00:00.000Z",
    tags: ["Low Energy", "Quiet", "Needs Encouragement"],
    interests: ["Classic cars", "Old westerns"],
    dislikes: ["Crowded spaces"],
    favoriteActivities: ["Car photo trivia", "Movie chat"],
    favoriteTopics: ["Restoration stories", "Road trips"],
    favoriteMusic: ["Johnny Cash"],
    favoriteMedia: ["Classic western movies"],
    independentActivities: ["Car magazines"],
    participationStyle: "Initially hesitant; engages once rapport is built",
    bestTimeOfDay: "Mid-afternoon",
    groupParticipationNotes: "May observe first and join if prompted.",
    oneToOneStyle: "Stronger engagement with car-related prompts.",
    commonRefusals: "Declines noisy or high-movement activities.",
    whatWorks: "Offer familiar car topics and shorter sessions.",
    whatDoesNotWork: "Large high-energy circles.",
    supportNeeds: ["Prefers Quiet Setting", "Low Energy", "Needs Cueing"],
    quickSummary: "Initially hesitant; engages once rapport is built",
    sourceNotes: null,
    sourcePreferences: null,
    sourceSafetyNotes: null,
    lastEngagementDate: daysAgo(5),
    lastActivity: "Observed auto-trivia, then answered with encouragement.",
    lastOneToOne: "Discussed classic cars using magazine prompts.",
    lastNoteDate: daysAgo(4),
    lastAiSuggestion: "Prepare a 1:1 classic-cars memory card set.",
    dischargeDate: null,
    dischargeReason: null
  },
  {
    id: "mock-8",
    firstName: "Joan",
    lastName: "Fletcher",
    fullName: "Joan Fletcher",
    preferredName: "Joanie",
    room: "130A",
    status: "DISCHARGED",
    admissionDate: "2025-07-09T00:00:00.000Z",
    birthDate: "1942-11-29T00:00:00.000Z",
    tags: ["Crafts", "Family-Oriented", "Archived"],
    interests: ["Card making", "Family photos"],
    dislikes: ["Fast transitions"],
    favoriteActivities: ["Seasonal cards"],
    favoriteTopics: ["Grandchildren"],
    favoriteMusic: ["60s pop"],
    favoriteMedia: ["Romantic comedies"],
    independentActivities: ["Sticker books"],
    participationStyle: "Warm engagement in quiet craft settings",
    bestTimeOfDay: "Morning",
    groupParticipationNotes: "Preferred table craft groups.",
    oneToOneStyle: "Enjoyed family-photo conversations.",
    commonRefusals: "Declined loud afternoon events.",
    whatWorks: "Offer creative tasks with clear setup.",
    whatDoesNotWork: "Large noisy groups.",
    supportNeeds: ["Prefers Quiet Setting", "Better in Small Groups"],
    quickSummary: "Warm engagement in quiet craft settings",
    sourceNotes: null,
    sourcePreferences: null,
    sourceSafetyNotes: null,
    lastEngagementDate: daysAgo(18),
    lastActivity: "Completed farewell card activity before discharge.",
    lastOneToOne: "Discussed return-home transition with family updates.",
    lastNoteDate: daysAgo(17),
    lastAiSuggestion: "N/A",
    dischargeDate: "2026-03-28",
    dischargeReason: "Returned Home"
  }
];
