"use client";

import { useEffect, useMemo, useState } from "react";

type SettingsSection = "profile" | "facility" | "assistant" | "reports" | "notifications" | "subscription" | "security";

type SafeSettingsDraft = {
  displayName: string;
  jobTitle: string;
  facilityName: string;
  timezone: string;
  assistantStyle: string;
  reportFooter: string;
  notificationsEnabled: boolean;
  dataMode: string;
};

const STORAGE_KEY = "actify:safe-settings-draft";

const defaultDraft: SafeSettingsDraft = {
  displayName: "",
  jobTitle: "Activities Director",
  facilityName: "Actify Facility",
  timezone: "America/Chicago",
  assistantStyle: "PCC-ready and state-ready documentation support",
  reportFooter: "Generated by Actify",
  notificationsEnabled: true,
  dataMode: "Activity Director workflow support"
};

const sections: Array<{ key: SettingsSection; label: string; description: string }> = [
  { key: "profile", label: "Profile", description: "Your basic Actify workspace preferences." },
  { key: "facility", label: "Facility", description: "Facility name and timezone defaults." },
  { key: "assistant", label: "AI Assistant", description: "Documentation and planning style preferences." },
  { key: "reports", label: "Reports", description: "Print-ready report defaults." },
  { key: "notifications", label: "Notifications", description: "Reminder preferences." },
  { key: "subscription", label: "Subscription", description: "Plan and billing access." },
  { key: "security", label: "Security", description: "Data and account safety information." }
];

function readDraft() {
  try {
    const raw = window.localStorage.getItem(STORAGE_KEY);
    if (!raw) return defaultDraft;
    return { ...defaultDraft, ...JSON.parse(raw) } as SafeSettingsDraft;
  } catch {
    return defaultDraft;
  }
}

function fieldClass() {
  return "mt-2 h-11 w-full rounded-2xl border border-slate-200 bg-white px-3 text-sm text-slate-900 outline-none transition focus:border-emerald-400 focus:ring-2 focus:ring-emerald-100";
}

function labelClass() {
  return "text-sm font-semibold text-slate-800";
}

export function SafeSettingsWorkspace({ initialSection }: { initialSection: SettingsSection }) {
  const [activeSection, setActiveSection] = useState<SettingsSection>(initialSection);
  const [draft, setDraft] = useState<SafeSettingsDraft>(defaultDraft);
  const [savedMessage, setSavedMessage] = useState("");

  useEffect(() => {
    setDraft(readDraft());
  }, []);

  useEffect(() => {
    setActiveSection(initialSection);
  }, [initialSection]);

  const activeMeta = useMemo(() => sections.find((section) => section.key === activeSection) ?? sections[0], [activeSection]);

  function update<K extends keyof SafeSettingsDraft>(key: K, value: SafeSettingsDraft[K]) {
    setDraft((current) => ({ ...current, [key]: value }));
    setSavedMessage("");
  }

  function saveDraft() {
    try {
      window.localStorage.setItem(STORAGE_KEY, JSON.stringify(draft));
      setSavedMessage("Settings saved on this device.");
    } catch {
      setSavedMessage("Settings could not be saved in this browser.");
    }
  }

  return (
    <main className="flex-1 space-y-5">
      <section className="rounded-[2rem] border border-emerald-900/10 bg-white/88 p-5 shadow-[0_24px_50px_-38px_rgba(15,23,42,0.45)] backdrop-blur md:p-6">
        <p className="text-xs font-semibold uppercase tracking-[0.16em] text-emerald-700">Actify settings</p>
        <h1 className="mt-1 text-3xl font-black text-slate-950">Settings</h1>
        <p className="mt-2 max-w-3xl text-sm leading-6 text-slate-600">
          Manage core Actify preferences from a safe, lightweight settings page. This page intentionally stays outside the EHR-style workflow and keeps Actify focused on Activity Director operations.
        </p>
        <div className="mt-4 rounded-2xl border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-900">
          Settings are currently opening in safe mode so the page loads reliably. Changes saved here are stored on this device while database-backed settings are stabilized.
        </div>
      </section>

      <section className="grid gap-4 lg:grid-cols-[280px_minmax(0,1fr)]">
        <aside className="rounded-[1.6rem] border border-slate-200 bg-white/88 p-2 shadow-sm">
          {sections.map((section) => (
            <button
              key={section.key}
              type="button"
              onClick={() => setActiveSection(section.key)}
              className={section.key === activeSection ? "mb-1 w-full rounded-2xl bg-slate-950 px-3 py-3 text-left text-white" : "mb-1 w-full rounded-2xl px-3 py-3 text-left text-slate-700 transition hover:bg-slate-50"}
            >
              <span className="block text-sm font-bold">{section.label}</span>
              <span className={section.key === activeSection ? "mt-0.5 block text-xs text-slate-300" : "mt-0.5 block text-xs text-slate-500"}>{section.description}</span>
            </button>
          ))}
        </aside>

        <section className="rounded-[1.6rem] border border-slate-200 bg-white/90 p-5 shadow-sm md:p-6">
          <div className="flex flex-wrap items-start justify-between gap-3">
            <div>
              <p className="text-xs font-semibold uppercase tracking-[0.14em] text-slate-500">{activeMeta.label}</p>
              <h2 className="mt-1 text-2xl font-black text-slate-950">{activeMeta.description}</h2>
            </div>
            <button type="button" onClick={saveDraft} className="rounded-full bg-emerald-900 px-4 py-2 text-sm font-bold text-white transition hover:bg-emerald-800">
              Save Settings
            </button>
          </div>

          {savedMessage ? <p className="mt-4 rounded-2xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-800">{savedMessage}</p> : null}

          <div className="mt-6 space-y-5">
            {activeSection === "profile" ? (
              <div className="grid gap-4 md:grid-cols-2">
                <label className={labelClass()}>Display name<input className={fieldClass()} value={draft.displayName} onChange={(event) => update("displayName", event.target.value)} placeholder="Your name" /></label>
                <label className={labelClass()}>Job title<input className={fieldClass()} value={draft.jobTitle} onChange={(event) => update("jobTitle", event.target.value)} /></label>
              </div>
            ) : null}

            {activeSection === "facility" ? (
              <div className="grid gap-4 md:grid-cols-2">
                <label className={labelClass()}>Facility name<input className={fieldClass()} value={draft.facilityName} onChange={(event) => update("facilityName", event.target.value)} /></label>
                <label className={labelClass()}>Timezone<input className={fieldClass()} value={draft.timezone} onChange={(event) => update("timezone", event.target.value)} /></label>
              </div>
            ) : null}

            {activeSection === "assistant" ? (
              <label className={labelClass()}>Assistant style<textarea className="mt-2 min-h-32 w-full rounded-2xl border border-slate-200 bg-white p-3 text-sm text-slate-900 outline-none transition focus:border-emerald-400 focus:ring-2 focus:ring-emerald-100" value={draft.assistantStyle} onChange={(event) => update("assistantStyle", event.target.value)} /></label>
            ) : null}

            {activeSection === "reports" ? (
              <label className={labelClass()}>Default report footer<input className={fieldClass()} value={draft.reportFooter} onChange={(event) => update("reportFooter", event.target.value)} /></label>
            ) : null}

            {activeSection === "notifications" ? (
              <label className="flex items-center justify-between gap-4 rounded-2xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm font-semibold text-slate-800">
                Enable activity reminders
                <input type="checkbox" checked={draft.notificationsEnabled} onChange={(event) => update("notificationsEnabled", event.target.checked)} className="h-5 w-5 accent-emerald-700" />
              </label>
            ) : null}

            {activeSection === "subscription" ? (
              <div className="rounded-2xl border border-slate-200 bg-slate-50 p-4 text-sm text-slate-700">
                <p className="font-semibold text-slate-900">Billing portal access is handled through the subscription page.</p>
                <a href="/subscribe" className="mt-3 inline-flex rounded-full bg-slate-950 px-4 py-2 text-sm font-bold text-white">View plan options</a>
              </div>
            ) : null}

            {activeSection === "security" ? (
              <label className={labelClass()}>Data mode<input className={fieldClass()} value={draft.dataMode} onChange={(event) => update("dataMode", event.target.value)} /></label>
            ) : null}
          </div>
        </section>
      </section>
    </main>
  );
}
