import { z } from "zod";

export const CALENDAR_BUILDER_PAPER_PRESETS = [
  "LETTER_PORTRAIT",
  "LETTER_LANDSCAPE",
  "LEGAL_PORTRAIT",
  "LEGAL_LANDSCAPE",
  "TABLOID_PORTRAIT",
  "TABLOID_LANDSCAPE"
] as const;

export const CALENDAR_BUILDER_LAYOUT_PRESETS = ["STANDARD_GRID", "HERO_BLANKS"] as const;
export const CALENDAR_BUILDER_FONT_SCALES = ["SM", "MD", "LG"] as const;

export const calendarBuilderDesignSchema = z.object({
  monthKey: z.string().regex(/^\d{4}-\d{2}$/),
  version: z.number().int().min(0).default(0),
  layoutPreset: z.enum(CALENDAR_BUILDER_LAYOUT_PRESETS).default("STANDARD_GRID"),
  paperPreset: z.enum(CALENDAR_BUILDER_PAPER_PRESETS).default("LETTER_LANDSCAPE"),
  title: z.string().max(120).default(""),
  subtitle: z.string().max(180).default("Activity Calendar"),
  disclaimer: z.string().max(220).default("Activities subject to change."),
  footer: z.string().max(220).default(""),
  accentColor: z.string().regex(/^#[0-9a-fA-F]{6}$/).default("#0ea5e9"),
  backgroundColor: z.string().regex(/^#[0-9a-fA-F]{6}$/).default("#f8fafc"),
  cellBackgroundColor: z.string().regex(/^#[0-9a-fA-F]{6}$/).default("#ffffff"),
  textColor: z.string().regex(/^#[0-9a-fA-F]{6}$/).default("#0f172a"),
  borderColor: z.string().regex(/^#[0-9a-fA-F]{6}$/).default("#38bdf8"),
  activityChipStyle: z.enum(["SOFT", "BOLD", "MINIMAL"]).default("SOFT"),
  fontScale: z.enum(CALENDAR_BUILDER_FONT_SCALES).default("MD"),
  showHolidays: z.boolean().default(true),
  holidayCategories: z
    .object({
      federal: z.boolean().default(true),
      religious: z.boolean().default(true),
      seasonal: z.boolean().default(true),
      "skilled-nursing": z.boolean().default(true)
    })
    .default({ federal: true, religious: true, seasonal: true, "skilled-nursing": true }),
  showBirthdays: z.boolean().default(true),
  showAges: z.boolean().default(false),
  compactEvents: z.boolean().default(true),
  autoFitText: z.boolean().default(true),
  updatedAt: z.string().optional()
});

export type CalendarBuilderPaperPreset = (typeof CALENDAR_BUILDER_PAPER_PRESETS)[number];
export type CalendarBuilderLayoutPreset = (typeof CALENDAR_BUILDER_LAYOUT_PRESETS)[number];
export type CalendarBuilderDesign = z.infer<typeof calendarBuilderDesignSchema>;

export type CalendarBuilderStore = {
  version: 1;
  designs: Record<string, CalendarBuilderDesign>;
};

export function normalizeMonthKey(value: string) {
  const normalized = value.trim();
  if (/^\d{4}-\d{2}$/.test(normalized)) return normalized;
  if (/^\d{4}-\d{2}-\d{2}$/.test(normalized)) return normalized.slice(0, 7);
  return null;
}

export function defaultCalendarBuilderDesign(monthKey: string, facilityName = "My Facility"): CalendarBuilderDesign {
  return calendarBuilderDesignSchema.parse({
    monthKey,
    title: facilityName,
    subtitle: "Activity Calendar",
    footer: "Generated by Actify"
  });
}

export function asCalendarBuilderDesign(value: unknown, monthKey: string, facilityName = "My Facility"): CalendarBuilderDesign {
  const fallback = defaultCalendarBuilderDesign(monthKey, facilityName);
  const parsed = calendarBuilderDesignSchema.partial().safeParse(value);
  if (!parsed.success) return fallback;
  return calendarBuilderDesignSchema.parse({
    ...fallback,
    ...parsed.data,
    monthKey
  });
}

function asRecord(value: unknown): Record<string, unknown> {
  if (!value || typeof value !== "object" || Array.isArray(value)) return {};
  return value as Record<string, unknown>;
}

export function getCalendarBuilderStore(printDefaultsJson: unknown): CalendarBuilderStore {
  const printDefaults = asRecord(printDefaultsJson);
  const rawStore = asRecord(printDefaults.calendarBuilder);
  const rawDesigns = asRecord(rawStore.designs);
  const designs: Record<string, CalendarBuilderDesign> = {};

  Object.entries(rawDesigns).forEach(([monthKey, rawDesign]) => {
    const normalizedMonth = normalizeMonthKey(monthKey);
    if (!normalizedMonth) return;
    designs[normalizedMonth] = asCalendarBuilderDesign(rawDesign, normalizedMonth);
  });

  return {
    version: 1,
    designs
  };
}

export function mergeCalendarBuilderStore(
  printDefaultsJson: unknown,
  store: CalendarBuilderStore
): Record<string, unknown> {
  return {
    ...asRecord(printDefaultsJson),
    calendarBuilder: store
  };
}

export function getPdfPaperOptions(preset: CalendarBuilderPaperPreset): {
  paperSize: "LETTER" | "A4" | "LEGAL" | "TABLOID";
  orientation: "portrait" | "landscape";
} {
  if (preset === "LEGAL_PORTRAIT") return { paperSize: "LEGAL", orientation: "portrait" };
  if (preset === "LEGAL_LANDSCAPE") return { paperSize: "LEGAL", orientation: "landscape" };
  if (preset === "TABLOID_PORTRAIT") return { paperSize: "TABLOID", orientation: "portrait" };
  if (preset === "TABLOID_LANDSCAPE") return { paperSize: "TABLOID", orientation: "landscape" };
  if (preset === "LETTER_PORTRAIT") return { paperSize: "LETTER", orientation: "portrait" };
  return { paperSize: "LETTER", orientation: "landscape" };
}
